// 예시 데이터. config.js의 API_URL이 비어 있을 때만 쓰여요. 앱, 만든 사람, 숫자는 모두 지어낸 것이에요.
window.APPTORI_SAMPLE = {
  ok: true,
  sample: true,
  apps: [
    { id: "wheel-runner", name: "쳇바퀴 러너", cat: "game", kind: "web", genre: "러너 게임", line: "끝없이 달리며 해바라기씨를 모아요", hero: "끝없이 달리는 햄스터, 오늘 기록은 몇 미터?", maker: "햄찌스튜디오", tool: "Claude", date: "2026-09-28",
      intent: "아이와 같이 할 수 있는 쉬운 게임을 만들고 싶었어요. AI에게 규칙을 설명하고 주말 이틀 만에 완성했어요.", target: "짧게 즐길 게임을 찾는 누구나. 버튼이 하나라 아이와 함께 하기 좋아요.",
      features: ["버튼 하나로 점프", "매일 바뀌는 코스", "기록을 이미지로 공유"], steps: ["화면을 눌러 점프해요", "씨앗을 모으면 속도가 올라가요", "끝나면 기록을 친구에게 보내요"],
      bg: "#4A1F2B", fg: "#FF9E7A", motif: "wheel", featured: true, isNew: true, tries: 1840, last: 920, shares: 64 },
    { id: "grocery-mate", name: "장보기 메이트", cat: "prod", kind: "web", genre: "살림", line: "냉장고 사진으로 장볼 목록을 만들어요", hero: "냉장고 한 장 찍으면, 오늘 장볼 목록 끝", maker: "부엌실험실", tool: "Lovable", date: "2026-09-26",
      intent: "냉장고에 뭐가 있는지 몰라 같은 걸 또 사는 일이 잦았어요.", target: "장보기를 맡은 살림꾼, 여럿이 함께 사는 집의 관리자",
      features: ["사진 한 장으로 재고 파악", "식단에 맞춘 장보기 목록", "가족과 목록 공유"], steps: ["냉장고 안을 찍어요", "부족한 재료를 확인해요", "목록을 가족에게 보내요"],
      bg: "#DCEBD2", fg: "#2F5A2A", motif: "basket", featured: true, isNew: true, tries: 1620, last: null, shares: 41 },
    { id: "word-fishing", name: "단어 낚시", cat: "game", kind: "web", genre: "단어 게임", line: "물 위에 뜬 뜻을 보고 영어 단어를 낚아요", hero: "단어장 대신 낚싯대, 하루 10단어", maker: "말랑영어", tool: "Cursor", date: "2026-09-20",
      intent: "단어장은 지루해서 게임으로 외우고 싶었어요.", target: "영어 단어를 놀면서 외우고 싶은 학생과 직장인",
      features: ["하루 10단어", "틀린 단어는 다음 날 다시", "난이도 3단계"], steps: ["물 위에 뜬 뜻을 읽어요", "맞는 단어 물고기를 눌러 낚아요", "틀린 단어는 내일 다시 나와요"],
      bg: "#12384A", fg: "#7FD3E8", motif: "waves", featured: true, tries: 1310, last: 1400, shares: 22 },
    { id: "dotori-2048", name: "도토리 2048", cat: "game", kind: "web", genre: "퍼즐", line: "같은 도토리를 합쳐 큰 도토리로", maker: "밤톨공방", tool: "Claude", date: "2026-09-24",
      intent: "쉬는 시간 3분에 끝나는 퍼즐이 필요해서 AI와 하루 만에 만들었어요.", target: "출퇴근길에 가볍게 머리를 식히고 싶은 분",
      features: ["한 판 3분", "광고 없음", "휴대폰 한 손 조작"], steps: ["화면을 밀어 도토리를 모아요", "같은 도토리가 만나면 합쳐져요", "칸이 꽉 차기 전에 큰 도토리를 만들어요"],
      bg: "#3B2A1E", fg: "#F4B43A", motif: "tiles", isNew: true, tries: 1180, last: null, shares: 30 },
    { id: "receipt-helper", name: "영수증 정리기", cat: "prod", kind: "web", genre: "가계부", line: "사진만 찍으면 지출표가 돼요", maker: "가계부연구소", tool: "Bolt", date: "2026-09-22",
      intent: "프리랜서로 일하며 영수증 정리에 주말을 쓰는 게 싫었어요.", target: "영수증이 쌓이는 프리랜서와 자영업자",
      features: ["사진 30장을 한 번에", "구글 시트로 내보내기", "지출 분류 자동 추천"], steps: ["영수증 사진을 올려요", "날짜와 금액이 맞는지 확인해요", "구글 시트로 내보내요"],
      bg: "#F1E7D6", fg: "#3A2A1C", motif: "receipt", isNew: true, tries: 990, last: null, shares: 18 },
    { id: "daily-riddle", name: "오늘의 수수께끼", cat: "game", kind: "web", genre: "퀴즈", line: "AI가 매일 하나씩 내는 수수께끼", maker: "퀴즈상점", tool: "Gemini", date: "2026-09-15",
      intent: "가족 단톡방에서 매일 같이 풀 거리가 있으면 좋겠다 싶었어요.", target: "가족, 친구와 가볍게 이야깃거리를 만들고 싶은 분",
      features: ["하루 한 문제", "힌트 3번", "정답 공유 카드"], steps: ["오늘의 문제를 읽어요", "막히면 힌트를 열어요", "정답 카드를 단톡방에 보내요"],
      bg: "#2E2A52", fg: "#C9B8FF", motif: "question", tries: 870, last: 1010, shares: 25 },
    { id: "meeting-3lines", name: "회의록 3줄", cat: "prod", kind: "web", genre: "업무 정리", line: "녹음 파일을 3줄 요약과 할 일로", maker: "오피스햄", tool: "Claude", date: "2026-09-12",
      intent: "회의는 1시간인데 정리에 30분씩 걸려서 만들었어요.", target: "회의가 잦은 팀장과 실무자",
      features: ["3줄 요약", "담당자별 할 일 정리", "보고용 존댓말로 정리"], steps: ["녹음 파일을 올려요", "요약과 할 일을 확인해요", "메일이나 메신저로 복사해요"],
      bg: "#1F2E3D", fg: "#9CC3F0", motif: "bars", tries: 760, last: 640, shares: 12 },
    { id: "pixel-farm", name: "픽셀 동물농장", cat: "game", kind: "mobile", genre: "방치형", line: "켜두기만 해도 동물이 자라는 농장", maker: "도트농부", tool: "Cursor", date: "2026-09-08",
      intent: "바쁜 날에도 잠깐 들여다볼 귀여운 게임을 원했어요.", target: "방치형 게임을 좋아하는 분",
      features: ["하루 두 번 접속이면 충분", "동물 24종", "꺼져 있어도 자라요"], steps: ["앱 마켓에서 내려받아요", "첫 동물을 골라요", "하루 두 번 먹이를 줘요"],
      bg: "#234027", fg: "#A8E06A", motif: "pixels", tries: 540, last: 700, shares: 9 },
    { id: "caption-helper", name: "캡션 도우미", cat: "prod", kind: "web", genre: "SNS 운영", line: "사진을 올리면 인스타 캡션 세 가지", maker: "피드공방", tool: "Lovable", date: "2026-09-05",
      intent: "매일 올리는 게시물마다 문구 고민이 너무 길었어요.", target: "매장 SNS를 직접 운영하는 사장님과 크리에이터",
      features: ["말투 3종 선택", "해시태그 추천", "글자 수 맞춤"], steps: ["사진을 올려요", "말투를 골라요", "마음에 드는 캡션을 복사해요"],
      bg: "#3D2440", fg: "#F2A7C8", motif: "spark", tries: 480, last: 300, shares: 15 },
    { id: "timetable-maker", name: "시간표 메이커", cat: "prod", kind: "web", genre: "일정", line: "일정 몇 개만 적으면 주간 시간표 완성", maker: "주간계획실", tool: "Gemini", date: "2026-08-30",
      intent: "학원, 운동, 약속이 뒤섞여 한눈에 보고 싶었어요.", target: "일정이 많은 학생과 학부모",
      features: ["겹치는 일정 자동 표시", "이미지로 저장", "색깔별 분류"], steps: ["일정을 말하듯 적어요", "만들어진 시간표를 확인해요", "이미지로 저장해요"],
      bg: "#E9E2F5", fg: "#4B3A78", motif: "calendar", tries: 350, last: 420, shares: 6 },
    { id: "formula-translator", name: "엑셀 수식 번역기", cat: "prod", kind: "pc", genre: "엑셀", line: "하고 싶은 일을 말하면 엑셀 수식으로", maker: "셀러리맨", tool: "Claude", date: "2026-08-21",
      intent: "수식 검색에 하루 30분씩 쓰던 시간을 줄이고 싶었어요.", target: "엑셀은 매일 쓰지만 수식은 어려운 직장인",
      features: ["한국어로 질문", "수식 설명도 함께", "엑셀 안에서 바로 실행"], steps: ["공식 사이트에서 설치해요", "엑셀에서 메뉴를 열어요", "하고 싶은 일을 적고 수식을 붙여넣어요"],
      bg: "#173A2C", fg: "#6FE0A8", motif: "formula", tries: 220, last: 260, shares: 3 }
  ]
};
